#ifndef __IFIRMWAREDOWNLOAD_H__
#define __IFIRMWAREDOWNLOAD_H__

typedef enum 
{
    RESULT_CONTINUE,
    RESULT_START_UPGRADE,
    RESULT_DONE,
    RESULT_STREAM_NOT_GOOD,
    RESULT_UNEXPECTED_RESPONSE,
    RESULT_DID_NOT_RECEIVE_IDENTIFICATION_RESPONSE_MESSAGE,
    RESULT_DID_NOT_RECEIVE_UPGRADE_RESPONSE_MESSAGE,
    RESULT_UPGRADE_RESPONSE_SIZE_TOO_BIG,
    RESULT_UPGRADE_RESPONSE_INVALID_MESSAGE,
    RESULT_UPGRADE_WRONG_DEVICE,
    RESULT_UPGRADE_UNSUPPORTED_ORDINAL,
    RESULT_UPGRADE_ERASE_FAILED,
    RESULT_UPGRADE_RESPONSE_INVALID_STATUS,
    RESULT_UPGRADE_RESPONSE_INVALID_WINDOW_SIZE,
    RESULT_UPGRADE_RESPONSE_IMAGE_ERROR,
    RESULT_UPGRADE_RESPONSE_CRC_ERROR,
    RESULT_UPGRADE_RESPONSE_FLASH_WRITE_ERROR,
    RESULT_DID_NOT_RECEIVE_DATA_TRANSFER_RESPONSE_MESSAGE,
    RESULT_READING_FIRMWARE_FILE_FAILED,
    RESULT_MAX_OUT_OF_SYNC_RETRIES_EXCEEDED,
    RESULT_DATA_TRANFER_WAIT_RSP
}eDownloadResult_t;



typedef enum 
{
		STATE_IDLE,
		STATE_WAITING_FOR_IDENTIFICATION_RESPONSE,
		STATE_WAITING_FOR_INITUPDATE_RESPONSE,
		STATE_WAITING_FOR_DATATRANSFER_RESPONSE,
		STATE_WAITING_FOR_DATATRANSFER_FINISH_RESPONSE
} eDownloadState_t;



















#endif // __IFIRMWAREDOWNLOAD_H__

